### ISSUE TITLE
Adapter#prompt doesn't return a promise

### ISSUE THREAD

**Issue by jrieken** [SamVerschueren/vscode-yo#42]
I am running in a type error as shown below and believe that's because `vscode-yo` doesn't return a promise from [`prompt`](https://github.com/SamVerschueren/vscode-yo/blob/master/src/yo/adapter.ts#L47) but yeoman-generator [expects](https://github.com/yeoman/generator/blob/master/lib/base.js#L240) that

```
Uncaught Exception:  TypeError: Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at Base.prompt (/Users/jrieken/Code/collab/generator-code-javascript/node_modules/yeoman-generator/lib/base.js:240:44)
    at prompting (/Users/jrieken/Code/collab/generator-code-javascript/generators/app/index.js:111:21)
    at Object.<anonymous> (/Users/jrieken/Code/collab/generator-code-javascript/node_modules/yeoman-generator/lib/base.js:439:23)
    at /Users/jrieken/Code/collab/generator-code-javascript/node_modules/run-async/index.js:26:25
```

**Comment by jrieken** [comment]
The generator in question: https://github.com/Microsoft/vscode-generator-code-javascript

**Comment by SamVerschueren** [comment]
Thanks for reporting! I will look into it when I find some time.

**Comment by jrieken** [comment]
Seems like yeoman now really depends on promises being passed around...

**Comment by jrieken** [comment]
yeah... https://github.com/yeoman/generator/releases/tag/v0.23.0

**Comment by SamVerschueren** [comment]
Fixed in `0.9.0`. Sorry for the delay, had some other priorities.
